### ISSUE TITLE
如何等待适配器启动后获取 Bot 对象

### ISSUE THREAD

**Issue by Umpire2018** [felinae98/nonebot-plugin-send-anything-anywhere#59]
使用：[Telegram ](https://github.com/nonebot/adapter-telegram)，  [APScheduler插件](https://nb2.baka.icu/docs/best-practice/scheduler)

当前我希望在插件中获取到适配器的 Bot 对象 并使用发送消息命令，代码如下
```python

from nonebot_plugin_apscheduler import scheduler 
from nonebot_plugin_saa import TargetTelegramCommon, MessageFactory
from nonebot_plugin_saa.utils import enable_auto_select_bot

@driver.on_bot_connect
async def do_something():
    enable_auto_select_bot()
    @scheduler.scheduled_job("cron", second='*/1', id="job_1")
    async def send_message():
        await MessageFactory("早上好").send_to(TargetTelegramCommon(chat_id='123456'))
```
查看 `auto_select_bot.py` 发现定义了 Hook 在bot 连接后来进行获取，但在以上用例中抛出了 `nonebot_plugin_saa.utils.exceptions.NoBotFound` 

请问如何正确获取 Bot 对象?

**Comment by felinae98** [comment]
tg 不支持获取已加入群聊的方法，可以使用`nonebot.get_bot`
